In [38]:
import keras_model
import parameter
import cls_data_generator
import numpy as np
from tf.keras import Input

ModuleNotFoundError: No module named 'tf'

In [3]:
# use parameter set defined by user
task_id = '1'
params = parameter.get_params(task_id)

data_gen_train = cls_data_generator.DataGenerator(
    dataset=params['dataset'], ov=params['overlap'], split=params['split'], db=params['db'], nfft=params['nfft'],
    batch_size=params['batch_size'], seq_len=params['sequence_length'], classifier_mode=params['mode'],
    weakness=params['weakness'], datagen_mode='train', cnn3d=params['cnn_3d'], xyz_def_zero=params['xyz_def_zero'],
    azi_only=params['azi_only']
)

data_in, data_out = data_gen_train.get_data_sizes()

model = keras_model.get_model(data_in=data_in, data_out=data_out, dropout_rate=params['dropout_rate'],
                              nb_cnn2d_filt=params['nb_cnn2d_filt'], pool_size=params['pool_size'],
                              rnn_size=params['rnn_size'], fnn_size=params['fnn_size'],
                              classification_mode=params['mode'], weights=params['loss_weights'])

SET: 1
USING DEFAULT PARAMETERS

quick_test: False
azi_only: True
dataset: ansim
overlap: 1
split: 1
db: 30
nfft: 512
sequence_length: 512
batch_size: 8
dropout_rate: 0.0
nb_cnn2d_filt: 64
pool_size: [8, 8, 2]
rnn_size: [128, 128]
fnn_size: [128]
loss_weights: [1.0, 50.0]
xyz_def_zero: True
nb_epochs: 10
mode: regr
nb_cnn3d_filt: 32
cnn_3d: False
weakness: 0
patience: 1
Datagen_mode: train, nb_files: 76, nb_classes:11
nb_frames_file: 5166, feat_len: 256, nb_ch: 8, label_len:33

Dataset: ansim, ov: 1, split: 1
batch_size: 8, seq_len: 512, shuffle: True
label_dir: data/label_ov1_split1_nfft512_regr0
 feat_dir: data/spec_ov1_split1_30db_nfft512_norm









Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 8, 51

In [4]:
model.load_weights('models/ansim_ov1_split1_regr0_3d0_1_model.h5')

In [58]:
test_audio = np.load('data/spec_ov1_split1_30db_nfft512_norm/test_0_desc_30_100.wav.npy')
test_audio2 = np.load('data/spec_ov1_split1_30db_nfft512_norm/test_3_desc_30_100.wav.npy')
test_label = np.load('data/label_ov1_split1_nfft512_regr0/test_0_desc_30_100.wav.npy')
print(test_label[40])

[  0.   0.   0.   0.   0.   0.   1.   0.   0.   0.   0. 180. 180. 180.
 180. 180. 180.  20. 180. 180. 180. 180.  60.  60.  60.  60.  60.  60.
 -40.  60.  60.  60.  60.]


In [5]:
data_gen_test = cls_data_generator.DataGenerator(
        dataset=params['dataset'], ov=params['overlap'], split=params['split'], db=params['db'], nfft=params['nfft'],
        batch_size=params['batch_size'], seq_len=params['sequence_length'], classifier_mode=params['mode'],
        weakness=params['weakness'], datagen_mode='test', cnn3d=params['cnn_3d'], xyz_def_zero=params['xyz_def_zero'],
        azi_only=params['azi_only'], shuffle=False
)

predictions = model.predict_generator(generator=data_gen_test.generate(), steps=1)
#np.shape(test_audio)

Datagen_mode: test, nb_files: 13, nb_classes:11
nb_frames_file: 5166, feat_len: 256, nb_ch: 8, label_len:33

Dataset: ansim, ov: 1, split: 1
batch_size: 8, seq_len: 512, shuffle: False
label_dir: data/label_ov1_split1_nfft512_regr0
 feat_dir: data/spec_ov1_split1_30db_nfft512_norm



In [91]:
print(test_audio[0])

2048


In [20]:
print(len(neu[0]))

8


In [62]:
neu = np.reshape(test_audio, (5166, 256, 8))

neu_rs = []
tmp = 0
batch = []
for inp in neu:
    neu_rs.append(inp)
    tmp += 1
    if tmp >= 512:
        #model.predict([np.reshape(neu_rs, (8, 512, 256))])
        #batch.append(np.reshape(neu_rs, (8, 512, 256)))
        new_predictions = model.predict(np.expand_dims(np.reshape(neu_rs, (8, 512, 256)), axis=0))
        #model.predict(batch)
        #print(np.shape(tf.keras.Input(np.reshape(neu_rs, (8, 512, 256))))
        tmp = 0
        neu_rs = []
        batch = []
        break
#print(np.shape(batch))
#model.predict(batch)
#print(np.shape(np.reshape(neu_rs, (8, 512, 256))))

In [63]:
print(new_predictions)

[array([[[0.10040134, 0.10847697, 0.09668654, ..., 0.12222797,
         0.06297112, 0.14493513],
        [0.09625193, 0.10628864, 0.08967954, ..., 0.11556467,
         0.05881506, 0.14209202],
        [0.09407234, 0.10562417, 0.08481857, ..., 0.11112007,
         0.056364  , 0.14099485],
        ...,
        [0.0931735 , 0.10796142, 0.07708457, ..., 0.10515141,
         0.05444062, 0.14148113],
        [0.0974195 , 0.1101017 , 0.08435312, ..., 0.11217061,
         0.05860743, 0.14447221],
        [0.10749951, 0.11593232, 0.09924752, ..., 0.12653878,
         0.06801394, 0.1521351 ]]], dtype=float32), array([[[ 0.00068963, -0.01358124, -0.00539521, ..., -0.00024626,
         -0.00116577,  0.03288512],
        [ 0.00036365, -0.01298683, -0.00403813, ...,  0.00104513,
          0.00031336,  0.03434487],
        [ 0.00029305, -0.01209521, -0.00192939, ...,  0.00211199,
          0.00217814,  0.03573678],
        ...,
        [-0.00076236, -0.00039548,  0.0060286 , ...,  0.00196131,
       

In [ ]:
print()

In [61]:
print(len(doa_out[0]))

512


In [97]:
data_gen_test.generate()

<generator object DataGenerator.generate at 0x13caa55d0>

In [94]:
model.predict_generator()
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 8, 512, 256)  0                                            
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 64, 512, 256) 4672        input_1[0][0]                    
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 64, 512, 256) 1024        conv2d_1[0][0]                   
__________________________________________________________________________________________________
activation_1 (Activation)       (None, 64, 512, 256) 0           batch_normalization_1[0][0]      
__________________________________________________________________________________________________
max_poolin

In [82]:
print(len(predictions[0][0]))

512


In [64]:
sed_out = new_predictions[0]
doa_out = new_predictions[1]

In [69]:
print(len(sed_out[0][0]))
print(doa_out[0][40])

11
[-0.00285949 -0.00083424  0.01197339 -0.01204813 -0.00329431 -0.00719987
 -0.0072041   0.03573935 -0.00153663  0.00616947 -0.02822786 -0.00380433
  0.02490557  0.01582198  0.01218127 -0.00189966  0.06040578  0.01883446
  0.00458244  0.01403117  0.01748819  0.05152611]


In [8]:
np.shape(sed_out)

(8, 512, 11)

In [7]:
np.shape(doa_out)

(8, 512, 22)

In [23]:
labels = ['Clearing throat', 'Coughing', 'Door knock', 'Door slam', 'Drawer', 'Human laughter', 'Keyboard', 'Keys', 'Page turning', 'Phone ringing', 'Speech']

In [47]:
sed_sum = [[0 for col in range(len(sed_out[0][0]))] for row in range(len(sed_out[0]))]
#print(len(sed_out[0][0]))
#print(sed_sum)
for channel in sed_out:
    sed_sum += channel
sed_avg = sed_sum / 11

for i in range(len(sed_avg)):
    
    print(f"{i}:\t{sed_avg[i]}\n")

0:	[0.00773022 0.00871993 0.00749646 0.00658055 0.00305807 0.01568407
 0.01350328 0.01001177 0.00973753 0.00463177 0.01184045]

1:	[0.00699471 0.0081914  0.00655597 0.00495917 0.00247437 0.01439313
 0.01279801 0.00919666 0.00879406 0.00401627 0.01116101]

2:	[0.00703411 0.00831577 0.00636077 0.00422519 0.0023489  0.01435361
 0.01305828 0.00927728 0.00866552 0.00398977 0.01123659]

3:	[0.00732046 0.00864739 0.00639996 0.00379883 0.00236101 0.01470861
 0.01362161 0.00964776 0.00879476 0.00414698 0.0115459 ]

4:	[0.00760154 0.0089618  0.0064658  0.00350708 0.00239044 0.01505934
 0.01414813 0.01001735 0.00894347 0.00431051 0.01183327]

5:	[0.00777082 0.00917314 0.00645644 0.00323312 0.00237809 0.01523819
 0.01451241 0.01025746 0.00899897 0.00439787 0.01200408]

6:	[0.00788468 0.00932996 0.00642843 0.00301581 0.00235647 0.01534259
 0.01478657 0.01042763 0.00902773 0.0044515  0.01212561]

7:	[0.00807252 0.00953767 0.00649358 0.00292511 0.00239013 0.01558109
 0.01512278 0.01066605 0.00915267 

In [48]:
for frame in sed_sum:
    classes = []
    for i in range(len(frame)):
        prediction = frame[i]
        if prediction > 0.5:
            classes.append(labels[i])
    print(classes)
        

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[

In [18]:
sed_out[1][200]

array([0.00207332, 0.00720775, 0.00164512, 0.00027534, 0.00010213,
       0.00682235, 0.01133978, 0.00399029, 0.00421464, 0.00045088,
       0.01333377], dtype=float32)

In [51]:
doa_out[][0]

array([-0.00210638, -0.01237567, -0.00439491, -0.01345185, -0.00374101,
        0.00111211, -0.00771918,  0.01247102, -0.00772113,  0.00386641,
       -0.01633441,  0.00040214,  0.01082385,  0.00912708,  0.01792912,
        0.00030994,  0.02469237,  0.00620004,  0.00172969, -0.00231528,
        0.00075454,  0.02750335], dtype=float32)

In [60]:
len(predictions[0])

16

In [74]:
np.shape(predictions[15])

IndexError: list index out of range

In [58]:
predictions[0][0]

array([[0.49590808, 0.4981138 , 0.49339366, ..., 0.49100006, 0.4966396 ,
        0.49456966],
       [0.49962074, 0.49811396, 0.49278373, ..., 0.48784795, 0.49544704,
        0.49334785],
       [0.5035278 , 0.49842638, 0.49163267, ..., 0.48409715, 0.4947161 ,
        0.4907665 ],
       ...,
       [0.50315696, 0.49541554, 0.49021712, ..., 0.48141867, 0.49631077,
        0.48821133],
       [0.4990536 , 0.49629346, 0.4916401 , ..., 0.48627734, 0.49603838,
        0.4919108 ],
       [0.49581704, 0.49735275, 0.49296165, ..., 0.49003696, 0.4962907 ,
        0.49426448]], dtype=float32)